=== mff-uk/exolutio/OclX/Examples/Dynamic/SchemaAware/TournamentApplication.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- generated by eXolutio on 26.2.2012 8:51 from tournaments/TournamentApplication. -->
  <xs:element name="tournamentApplication" type="Tournament" />
  <xs:complexType name="Tournament">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="requiredQualificationPoints" type="xs:nonNegativeInteger" minOccurs="0" />
      <xs:element name="player" type="Player" />
      <xs:element name="tournamentLeague" type="League" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Player">
    <xs:sequence>
      <xs:element name="points" type="xs:integer" />
      <xs:element name="regNo" type="xs:string" minOccurs="0" />
      <xs:element name="email" type="xs:string" minOccurs="0" />
      <xs:element name="name" type="xs:string" />
      <xs:element name="playerLeague" type="PlayerLeague" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="League">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PlayerLeague">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== mff-uk/exolutio/OclX/Examples/Functional/SchemaAware/TournamentApplication.xml
<?xml version="1.0" encoding="UTF-8"?>
<tournamentApplication
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   
  xsi:noNamespaceSchemaLocation="TournamentApplication.xsd">
  <name>Springfield Open</name>
  <requiredQualificationPoints>21</requiredQualificationPoints>
  <player>
    <points>24</points>
    <regNo>002</regNo>
    <name>John Smith</name>
    <playerLeague>
      <name>Springfield League</name>
    </playerLeague>
  </player>
  <tournamentLeague>
    <name>Springfield League</name>
  </tournamentLeague>
</tournamentApplication>
